Added login page, vite and made small changes
msaivasanth/Product-Inventory pull request #2
Opened 2024-04-03 16:45 UTC by msaivasanth

Added login page and vite sever to project 
Made small changes to some other files

2024-04-03 17:14 UTC, syedzeeshan1 requested changes
Overall looks good, minor changes are requested.

Also, try to see if you can deploy this app for free through some website like this - https://www.netlify.com/with/react/

This way I will also be able to look at UI and test e2e

2024-04-03 17:14 UTC, syedzeeshan1 commented on package-lock.json
>          "@types/react-dom": "^18.2.23",
create a .gitignore file and add package-lock.json to it.

files like this or node_modules should never be pushed to your repository.

2024-04-03 17:14 UTC, syedzeeshan1 commented on src/Components/Login.tsx
> +            const response = await fetch('https://dummyjson.com/auth/login', {
try to separate out API calls in a different service file. keep the code organized

2024-04-03 17:14 UTC, syedzeeshan1 commented on src/Components/Login.tsx
> +            // console.log(json.token)
nit: remove unnecessary comments

2024-04-04 15:19 UTC, merged

2024-04-05 00:46 UTC, syedzeeshan1 commented
@msaivasanth avoid merging without approval. 
LGTM, but why is the Vercel inspect check failing?

2024-04-05 03:52 UTC, msaivasanth commented
> @msaivasanth avoid merging without approval. LGTM, but why is the Vercel inspect check failing?

I apologize for merging without approval. Vercel inspect check failing because, first I deployed the project without merging the login branch at that time the project does not contain vite and at the deployment framework was react, after merging with login branch now it contains vite but the framework was still react for project, so the first check failed because it directly tried to deploy with merged commit which contains vite and framework was react in vercel. So I deleted the previous deployment and the I deployed the repository which now contains vite and specified vite as framework so second check was successful.